### ISSUE TITLE
Display levels behind SC title, shorten description for multi-level SCs

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#104]
1. Suggest change:
> Level A to meet WCAG 2.0 Level A success criteria; Level AA to meet WCAG 2.0 Level A and AA success criteria; Level AAA to meet all WCAG 2.0 success criteria

to just:
> Level A, AA, AAA

2. Suggest moving the Level to after the SC text, before the implementing link. e.g., :
> **A.1.2.1: Accessibility Guidelines** &nbsp; _Level A,AA,AAA_ &nbsp; {Implementing A.1.2.1}
> **A.1.2.2: Platform Accessibility Services** &nbsp; _Level A_ &nbsp; {Implementing A.1.2.2}

rationale: better use of space. easier to associate. much easier to skim.

**Comment by hidde** [comment]
The reasons they were underneath:

* that rather long description for multi level SCs
* mimicks what we do in the spec text 

If we're changing this to just ‘Level A, AA, AAA’, I am more than happy to add it right behind the SC title, agreed that this is easier to scan.
