### ISSUE TITLE
[later] titles need fixing

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#106]
(e.g., no longer "ATAG Conformance Evaluation Report Tool") 

probably best to wait until h1s settled :-)

/me quickly skimmed WAI info pages and WAI tools (quick ref, eval tools list, wcag-em report tool ...)

Other tool titles need fixing. We need to standardize.

I'm (mildly) thinking for tools:

page name | tool name | W3C WAI

**Comment by hidde** [comment]
Thanks. I like `page name | tool name | W3C WAI`. 

For reference, like on the WAI site we do  `page name | Web Accessibility Initiative (WAI) | W3C`, we could also use that pattern (with addition of `'| tool name'`)? I don't feel strong about it.

**Comment by slhenry** [comment]
mild -1 for written out "Web Accessibility Initiative" for tools -- just don't think it's worth the extra long words

**Comment by hidde** [comment]
Ok, agreed, less is more! 

In https://github.com/w3c/wai-atag-report-tool/issues/56, @nitedog expressed preference for actually having just the ATAG number in the page title, so I've done that just now.\

I've updated page titles to be `page name | ATAG Report Tool | W3C WAI`.

That should close this issue, feel free to reopen if you do want to add more thoughts or tweak.
