### ISSUE TITLE
Sync evaluation with localStorage: useful or confusing?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#107]
In ART, your evaluation is _autosaved_ in your browser (using `localStorage`). Whenever you change a result or add an observation, `localStorage` is updated. Whenever you open ART, it checks if you have any existing data in `localStorage`, and if so, it uses that. 

Questions for this issue: 

1. is saving all form data in the browser useful or confusing? 
2. is the way we do it now (save and restore automatically, have 'clear' in evaluation box) good or do we want to do it in a better way ([jump to ideas](#ideas))?

(I also did a [Twitter poll](https://twitter.com/hdv/status/1255478162105958402) which got a number of votes)

## Key benefits

* Data not gone on browser refresh or crash
* Easier to resume work on an evaluation without having to explicitly import/export

## Possible downsides

* Confusing if not transparent ([evaluation box]( is designed to mitigate this problem, as it clearly shows there is something existing, in a way that is hard to miss)
* Security: if the evaluation is sensitive, and it is done on a public or shared computer, the evaluation data is accessible by others using the same browser on the same domain

### OS/browser auto-update

1. Quinten wants to write a report about PerfectCMS 2.0. He has gathered some information, and starts ART.
2. A few hours in, his computer wants to an automated update. Perfect, as he just wanted to make a new cup of tea. He runs the update, returns with tea…
3. a. He opens his browser. The evaluation is gone, he needs to start over.
    b. He opens his browser. The evaluation is still there.

### Browser crash

1. Elina is working on a report for easyLearnPro. She's done 40 out of 52 criteria. 
2. For one specific SC, she needs to Google and ends up on a blog with lots of ads. It crashes her browser.
3. a. The browser reopens, the evaluation is gone, she needs to start over.
    b. The browser reopens, the evaluation is still there, she can continue her work.

### Browser refresh

1. Sarah needs to create a report on WFEA, a new WYSIWYG editor. She is almost  halfway.
2. She accidentally hits the refresh key. Because ART is an application that runs entirely in the browser, this may throw away all her data.
3. a. After refresh, the evaluation is still there, because it was saved in `localStorage`.
    b. After refresh, the evaluation is gone, because nothing saved it.
    c. A warning shows, “You may lose data”. If she chooses 'OK', her data is gone, if she chooses 'Cancel' she stays on the page and the refresh is cancelled.

### New report on colleague's computer

1. Ed borrowed the computer of his colleague. They are both authoring tool accessibility experts and create a lot of reports.
2. When he opens ART, he sees lots of results are already filled in. The Evaluation Box, he sees the evaluation also already has a name. 
3. a. He presses ‘Clear’ so that the data is cleared and he can start afresh.
    b. He was not supposed to see this, and uses the fact that he saw this report for bad purposes.
    c.  He is not sure what to do and just changes all the values in the tool, ignoring the 'Clear' option

## Context 

This feature benefits from the [“evaluation box” feature](https://github.com/w3c/wai-atag-report-tool/releases/tag/v0.2.0), because it makes clear that the state of evaluation: are we starting from scratch or is there something existing?
 
Example, something existing was loaded from `localStorage`: 

<img width="278" alt="evaluation box that shows evaluating Drupal with 9 out of 52 criteria checked" src="https://user-images.githubusercontent.com/178782/80601514-37f2a900-8a2e-11ea-82fc-a503ec8e6416.png">

Nothing was loaded:

<img width="281" alt="evaluation box that has Start New Evaluation and Import Evaluation buttons" src="https://user-images.githubusercontent.com/178782/80601901-b64f4b00-8a2e-11ea-949d-af4b77f4bfca.png">

<a name="ideas"></a>
### Explicit opt-in

Allow users to opt-in, for instance, only start saving if user checks a checkbox (eg “Save data locally while evaluating”)

<img width="584" alt="checkbox + text Save my input in my browser while I work on this evaluation" src="https://user-images.githubusercontent.com/178782/81403903-acb39a80-9134-11ea-914c-8021c51da9e4.png">

### Restoring as explicit action

Instead of restoring data automatically, make restoring an explicit action (eg “Existing evaluation “PerfectCMS” stored in your browser. [Restore button] [Dismiss button]”)

<img width="1098" alt="" src="https://user-images.githubusercontent.com/178782/81404364-978b3b80-9135-11ea-9799-a8f7f2e67639.png">

**Comment by bakkenb** [comment]
To me, pros outweigh the cons. With a little explanation in the overview we should be good to go.

**Comment by nitedog** [comment]
Based on the assumed [typical workflow for using this tool](https://github.com/w3c/wai-atag-report-tool/issues/99#issuecomment-621294269) (confirmed with @hidde), the "Save" and "Load" functions are the most critical and need to be easy to find at any time throughout the tool. Therefore this use of localStorage can be considered an enhancement, primarily for mishap situations (uninterruptable auto-update, crash, unintended refresh).

The main trade-off for this enhancement (in addition to time and effort to implement it), is that many people may not be used to finding old data they assumed to be deleted when they actively closed the browser to still exist. This does not seem to be typical behavior. In fact, some users may freak out to see old data still in the browser. I'm not aware of many web-based tools (that are not cloud-based) with such data-persistency behavior. I think such deviation from typical behavior/convention is quite an important issue.

Here are some possible options going forward in my view:

1. Provide explanation of this tool behavior on the Overview page, combined with a good presentation of the "Clear" function (will potentially require some testing with users to confirm clarity and usability of this rather unusual function/behavior)

2. In addition to 1, also trigger an alert box when users start/load the tool with data in localStorage -- they are asked if they want to continue with the old data or start a new session (could become quite intrusive and would ideally also require some testing)

3. Not use this localStorage function in version 1 of the tool, and instead use the more common behavior of triggering an alert box when tabs are closed with unsaved data (seems to also prevent unintended refresh and in some browsers auto-updates)

4. Develop some form of "smart restore", for example by only reloading data and/or alerting the user if it was not actively saved using the "Save" command (will potentially also require testing with users to make sure the behavior is not confusing)

For each of these, we need to consider the potential amount of effort needed to implement the feature in a usable way, and decide if we want/need to have it in version 1 or keep it as wishlist for future enhancements.

**Comment by mpalmersg** [comment]
From my experiences using the WCAG-EM reporting tool, autosaving to the browser is critical. While it may break with established, recognised behaviours, the pros far outweigh the cons. Losing data due to browser or OS crash, or simply forgetting to save manually, would potentially result in not only rekeying the data but possibly carrying out the associate check again.

**Comment by hidde** [comment]
@bakkenb Thanks for the response. I agree with the benefit of explanation at the start page. I think the trick here is to not overpromise, because availability of data in localStorage is at the browser's discretion (for instance, if you run low on disk space, browser may decide to empty it, more so in mobile devices than on desktop). What about “Evaluation data is saved in your browser's storage while you edit.”

@nitedog To clarify: the current situation is that evaluations _are_ saved in localStorage, that's what we'll have if we do no extra work. Removing the feature is a small amount of work, improving how it works medium amount of work.

@mpalmersg Thanks, noted that for you this feature is critical and pros outweigh cons I think the comparison with WCAG-EM Report Tool is fair, and the risk of having to add data or do checks multiple times is real.

**Comment by nitedog** [comment]
I don't disagree with the usefulness of this feature. Yet I have a feeling that finding a suitable UI/behavior for this rather uncommon feature is a non-trivial task. WCAG-EM Report Tool has existed for several years now, and this was not one of the requested features so far. Again, I don't disagree with usefulness of the feature but encourage us to think about the time and effort this would potentially take to develop in the first version of the tool, and balance that with the benefit of not further delaying the completion of a first version of the tool. Is this an essential feature for the first version of the tool?

**Comment by hidde** [comment]
I believe autosaving, plus:

* 'Clear' button in prominent place (the evaluation box)
* name of product you're evaluating in prominent place, to reiterate this is something existing and what kind of something(the evaluation box)
* explanation of the behavior first page

is a sound way to approach this, that is _not_ so uncommon. We currently have all of this (and have had it since the last two reviews), except the explanation on the first page.

Additionally, if we really feel this is confusing (so far the majority in this issue seems not to), we could make things more explicit, for instance in the ways I have mocked up in the [first comment above](https://github.com/w3c/wai-atag-report-tool/issues/107#issue-609039871) (see “Possible ways to improve”).

In the interest of not delaying completion, to be explciit: _removing_ the feature and replacing it with a warning, will take some time (in addition to losing the UX benefits mentioned by Mark above).

**Comment by lakeen** [comment]
I also think the pros outweigh the cons.  It's a great feature for an online evaluation form.  I'm more likely to use it knowing my work will not be lost if my connection goes down.

**Comment by AndrewArch** [comment]
My colleague currently doing some ATAG testing noted:
> “It’s good, keep this feature”. However, I didn’t realise it had this feature until reading the survey – maybe it’s worth adding a note about it to the Tips section in the Overview?

**Comment by hidde** [comment]
Thanks, it seems we are diverging towards _useful_ and want to keep this feature in.

@AndrewArch: 

What about adding this to the tip section: 

> While you report your findings, changes are saved in your browser (not on our servers). Export regularly to ensure you have your own copy.

**Comment by hidde** [comment]
Created after EOWG discussion: https://github.com/w3c/wai-atag-report-tool/issues/111

**Comment by hidde** [comment]
Have updated the explanatory text on Overview page to be: 

> This tools saves information you enter locally in your browser for backup (not on our servers).

which is EOWG's suggestion + '(not on our servers) for extra clarity.
