### ISSUE TITLE
copyedit note - spelling

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#108]
e.g., Organisation -> Organization

p.s. **empathy!**: I have studied in the UK (second time where I wrote lots of papers) and in the US, thus am personally aware the the challenges with different spellings (and words, date formats, etc.)

**Comment by hidde** [comment]
Thanks, good catch! 

Fwiw, I'm trying to stick to US English in this project, but write UK English anywhere else, so might accidentally slip in more English spelling.
