### ISSUE TITLE
Add conformance target selector

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#109]
Allow for users to set a conformance target, that can be set to A, AA or AAA (meaning 'up to and including').

Based on the value of the conformance target:

* Doing the evaluation, SCs that are _within_ the conformance target are shown. SCs that are not within the target are in an expand/collapse, hidden by default.
* In the Report page, JSON output and HTML output, we include: 
  * SCs that are within the conformance target
  * any SCs outside the conformance target that are filled in (because user opened the expand/collapse)

Examples:

* I selected Level AA. All Level AAA SCs are hidden by default in expand/collapse. During the evaluation I expand two AAA criteria and fill in some observations there. In the report, I see all A and AA SCs plus the two extra criteria
* I selected Level AAA. No SCs are in expand/collapse, everything is shown, both during evaluation and in the results.

cc @nitedog

**Comment by hidde** [comment]
@nitedog Question about the report. What about, instead of hiding items outside conformance target, we include them with “X was not in scope for this report“? This would make it more consistent then just leaving out. 

Example when conformance level is set to "A" (so all "AA" / "AAA" are out of scope).

<img width="708" alt="" src="https://user-images.githubusercontent.com/178782/81822473-73fc3280-9533-11ea-95fb-a1f4c5285312.png">

**Comment by nitedog** [comment]
Good idea, I like it. And if someone doesn't want it in the final HTML report, they can delete these lines (easier than adding back).
