### ISSUE TITLE
Missing w3c.json

### ISSUE THREAD

**Issue by plehegar** [w3c/wai-atag-report-tool#11]
See also https://w3c.github.io/w3c.json.html

**Comment by yatil** [comment]
Nudges this over to @hidde :-) #NotMyRepo

**Comment by hidde** [comment]
Thanks, on it!

**Comment by hidde** [comment]
Fixed in https://github.com/w3c/wai-atag-report-tool/commit/199870a02a51f63567ce0afbc5c3979b31879e5e
