### ISSUE TITLE
Reported numbers unclear

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-atag-report-tool#114]
The Evaluation Box includes the number of reported on success criteria.

But it may not be clear what this means. It seems that it is any SC that has a result or observation included. I may write observations without marking a result which means that I might think it hasn't been reported on yet.

Also, if I reset the result and observation that reported count does not go down.

**Comment by hidde** [comment]
The total means the total amount of items that have been ‘touched’ by the evaluator. When this was implemented, we did not have a way to reset to default, as there was no default (''--').

Do you think it should be the total amount of items that are not the default?

**Comment by iadawn** [comment]
I think there is scope to define what we mean by 'reported'. It seems the definition is a bit loose which, I think, reduces the value of the count.

**Comment by hidde** [comment]
The current technical definition is very strict, it is anything that you have changed the value of once or more.

I'm more than happy to consider a redefinition of what it means, if that better matches user's expectations.

**Comment by iadawn** [comment]
I get the technical definition... I am just not sure how that helps people. The goal of this seems to be something like a progress bar. As an auditor I would be looking for that to indicate what I was "done" with. I am not sure how easy it is to do that though as I might repeatedly revisit success criteria to review or add to.

I will confess to not having conducted an ATAG audit so I am basing this on my approach to WCAG audits. In that case I will work through pages rather than success criteria and build up the report that way. If ATAG allows for a more straight forward check one SC completely before moving onto the next SC approach then the reported count makes sense. If it allows for different approaches then I am not sure what it is doing for users.

**Comment by hidde** [comment]
It gives _some_ indication of that progress is happening, and how much of it. It allows for distinguishing between 'I'm almost there' vs 'I'm halfway' vs 'oh I should block a few more days in my agenda if I want this finished'. If you import an existing evaluation, that may be a helpful thing to reassure that you've imported the right file (“wait, didn't my colleague mention there was only one SC left, but this shows I still have 10 to go”). 

I would say compared to nothing at all, that is better.

**Comment by hidde** [comment]
> Also, if I reset the result and observation that reported count does not go down.

I've updated the definition, it now no longer counts items that have been reset to default (“--”), even if they had been touched before. I think you're right and this is clearer.

**Comment by hidde** [comment]
@iadawn With the updated counting method, that leaves your other concern: whether to mark results with observations only.

I understand the concern, we could change this to count SCs with either a result, or an observation (instead of the current counting method of only counting results). Would that address your concern?

**Comment by iadawn** [comment]
I think the result is the main thing. If it hasn't got a result then it isn't a reported SC.

**Comment by hidde** [comment]
Thanks, Kevin! 

I think I agree.

Do you think it is a common use case for observations to exist without results? Thinking about when I do evaluations, I think I'd be able to select a non-default result pretty much all of the time (but not selecting, forgetting to select… it probably happens, but maybe not enough to count it as a result in this counter).

**Comment by iadawn** [comment]
I think there will be instances where a Pass or N/A will have no observations. I can't imagine a Fail not having observations.

**Comment by hidde** [comment]
Agreed. In that case, it seems like only counting an SC as “reported” if there's a result if the best way forward?

**Comment by iadawn** [comment]
Agreed

**Comment by hidde** [comment]
In that case I will mark this issue as resolved! Thanks again for all the feedback!
