### ISSUE TITLE
Report page wording

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#129]
Reference: [Report page](https://atag-report-tool.hdv.now.sh/report)

From Hidde in https://github.com/w3c/wai-atag-report-tool/issues/65#issuecomment-638840994
> Looking forward to suggestions for “General”. I like “About” or “About this Evaluation”.

**Comment by slhenry** [comment]
_Here's an idea._

Page: https://atag-report-tool.hdv.now.sh/report
Nav: View Report
Page title & H1: Authoring Tool Accessibility Report
or maybe: Accessibility Report for [Tool Name]

{buttons:} [ Download report as HTML ]  [ Download report as JSON ]
## About the Evaluation
Authoring Tool Name
Website
Report Identifier
Conformance Target
Executive Summary
Evaluator Name
Evaluator Organization
[ Edit ]
## Results
This report has results for X out of XX Success Criteria.
{list …}
{Table}

---
That is, I don't think you need sub-headings under Results. .. If really think need sub-headings under Results, then:
Overview -> Summary
All results -> Details

**Comment by slhenry** [comment]
Although I don't like having two edit buttons and all those headings, I don't feel strongly. I'm OK with it as is.

Would be good in Work for this Week and/or the survey to specifically ask EOWG to consider the organization of information and headings on this page.

**Comment by hidde** [comment]
Thanks @slhenry. Will add this to the survey!
