### ISSUE TITLE
Tweaks to About page wording

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#134]
_While working on ideas for [Report page wording](https://github.com/w3c/wai-atag-report-tool/issues/129) and other issues, I also considered the start page, and have the following suggestion._

Page: https://atag-report-tool.hdv.now.sh/start
Nav: About
Page title & H1: About this Evaluation
## Authoring Tool
Name
Website (URL)
## Report
Report Identifier (i)
Conformance Target
Executive Summary (i)
## Evaluator
Name
Organization

**Comment by slhenry** [comment]
Note that we might want to provide a little help for "Report Identifier" (saying they can use default date, or use another date, or use a version number, or whatever they want) and "Executive Summary" (saying they can fill it out at the end of the evaluation on the Report page).

**Comment by hidde** [comment]
Thanks for the suggestion! I have updated the Start page to have the three sections as you suggested.

I strongly feel we should keep the page title, how it is called in the nav (and URL), and the `h1` the same. If “About” is better than “Start”,  can't we call it “About” in all of those places? “Start” is the result of a comprehensive WG disussion, I feel it works well. 

I like the idea of adding more information to report identifier and executive summary, but wonder whether we can design around that. Can we use words for “Report Identifier” and “Executive Summary” that are so clear that they don't further explanation?

I don't think we need to say that they can fill it out at the end of the evaluation, because it goes for every field in this tool that it can be filled out at any time. I don't know if all users will understand that, but my hope is that it will become clear from using the tool.

**Comment by nitedog** [comment]
I mostly agree:

1. If "About" is better, than let's use that. I do like it over "Start" but don't feel strongly.
2. Maybe worth-while exploring another name for "Report Identifier". Maybe spell it out, like "Report Date, Version, or Other Identifier"? Maybe too long?
3. Everything can be filled out at any time but the "Executive Summary" makes more sense to complete at the end of the process. I think it is somewhat different to the other fields and may need some explanation. However, maybe this can also be in-line (eg. "Executive Summary (to be completed at the end)" without any icons or such)?

**Comment by hidde** [comment]
In https://github.com/w3c/wai-atag-report-tool/issues/65, we have discussed other phrases for “Report Identifier”, including “Your Reference” (+1 from 1 person and -1 from 1 person), “Reference” (+1 from 1 person), “date of evaluation” and “report identifier”.

**Comment by hidde** [comment]
This is now done in https://github.com/w3c/wai-atag-report-tool/commit/ba2aa44b31ae55da4557ed785c5722a76dc48ebc.

**Comment by slhenry** [comment]
>  I still feel “Report Identifier” works best, because it is broader than just a date, broader than a version and clearer than reference.

+1 for “Report Identifier” as the field label as it's broad enough to cover whatever users want.

+1 that it needs explanation. Even though it's a good label, users might not know what it is for.

> help for "Report Identifier" (saying they can use default date, or use another date, or use a version number, or whatever they want)

options:
1. just have it on the first page user documentation
2. have it in (parenthesis) after the field label
3. have it display with click on (i) like in other tools

my input:
-1 for #1 -- it's less helpful out of context (and prefer not to include such low importance, single-context info on the main page)
+1 for either #2 or #3 so it's right there in context (slight preference for #3)

**Comment by slhenry** [comment]
> ...every field in this tool that it can be filled out at any time. I don't know if all users will understand that, but my hope is that it will become clear from using the tool.

Agree. So, let's tell them in the user documentation on the first page. :)

**Comment by hidde** [comment]
Regarding explanation:

* -1 for having it on the first page, agreed with less helpful out of context (and worried the longer that page will be, the less likely people will study it before starting)
* +1 for parenthesis (but would have to be super succinct or (i)

What about using this: 

<img width="740" alt="Report identifier label with blue info icon displayed at the end" src="https://user-images.githubusercontent.com/178782/84676177-7801e280-af2d-11ea-9be6-7b2473ed3184.png">

<img width="725" alt="Expanded info text, report identifier label with blue icon displayed" src="https://user-images.githubusercontent.com/178782/84676187-79cba600-af2d-11ea-869b-d973bb288461.png">

Content suggestions welcome!

**Comment by hidde** [comment]
Other suggestion: 

<img width="738" alt="Report Identifier (date, internal version number, etc.) " src="https://user-images.githubusercontent.com/178782/84879084-08a20500-b08b-11ea-8651-090ef51a86de.png">

**Comment by slhenry** [comment]
minor _mild_ suggestion:
> Report Identifier (date, internal version number, etc.)

->
> Report Identifier (date, internal version number, or other)

**Comment by nitedog** [comment]
Works for me.

**Comment by hidde** [comment]
Good change. Mildly feel we should not have an Oxford comma there, but happy to add if it's per style guide.

**Comment by slhenry** [comment]
> Oxford comma there, but happy to add if it's per style guide.

yeah, it is https://www.w3.org/WAI/EO/wiki/Style#Punctuation
