### ISSUE TITLE
[minor] headline-style capitalization for headings and buttons

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#135]
Our [Style Guide](https://www.w3.org/WAI/EO/wiki/Style#Capitalization) says:
> use headline-style capitalization (the first letter of major words is capitalized)

And exceptions are allowed.

For the ATAG wording, let's definitely keep their capitalization.

For the headings (h1, h2, etc) in the tool itself, let's do headline-style capitalization -- unless there's a compelling reason not to.

**Comment by hidde** [comment]
As a non-American, I find this very hard (what determines whether a word counts as major?)

I will follow the style guide though, and updated the ones I can find.

**Comment by hidde** [comment]
Have updated all headings, form labels and buttons to have headline-style capitalisation. 

For ATAG wording, as per your suggested, I've kept it as it is in [ATAG itself](https://www.w3.org/TR/ATAG20/): that means only headline-style in the success criteria names, but not in the principles or guidelines.
