### ISSUE TITLE
Change external links explaining Markdown

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#136]
first page currently has:
> You can format your evaluation with Markdown, so that you can use lists, links and code examples (read more about Markdown syntax).

linked to:
* https://en.wikipedia.org/wiki/Markdown
* https://daringfireball.net/projects/markdown/syntax#block

I think it's OK to link to wikipedia. Think not good to link to daringfireball.net or other such site.

I think the [Example](https://en.wikipedia.org/wiki/Markdown#Example) section of the wikipedia page is good enough. If people want more, they can find it themselves. It's beyond the scope of this tool to teach them Markdown.

**Comment by hidde** [comment]
It's the most official documentation of Markdown (published by its inventor), but agree it would be easy for anyone to find.
