### ISSUE TITLE
Improve field label styling

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#137]
I think the field labels should be Main text color --off-black (#1d1d1d)
These are currently not: Result, Evaluate as, Observations.

I _mildly_ think all field labels should end with a colon. They don't throughout the tool. I can be easily convinced that colon not needed. :)

**Comment by hidde** [comment]
With that black colour and a colon, I feel the labels become less subtle, I've reduced the font weight to mitigate.

<img width="782" alt="" src="https://user-images.githubusercontent.com/178782/84034874-37d5b980-a99b-11ea-86ca-e323cafa2b33.png">
