### ISSUE TITLE
[minor] font styling differences

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#139]
![image](https://user-images.githubusercontent.com/6991814/83836954-b809cf80-a6ba-11ea-885b-7c22ee6606c9.png)

Lots of different font styling on this page.

I commented in other issues on color.

Another place I can see to have less difference is to make the Level and the Implementing link the same size text. IN above:
> Level A, AA, AAA    Implementing A.1.1.1

**Comment by hidde** [comment]
You are right! This is now addressed, so that they both use the same size as buttons do in the WAI Components (~13px).
