### ISSUE TITLE
[Your Report widget] keep same functionality on the About (ex Start) page

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#144]
This stems from issue #60 

Issue: Right now, the "Your Report" widget on the right hand side displays a small summary of the results on all pages except the About/Start page, where it provides text mostly for people new to the tool. This seems confusing to me.

Suggestion: Keep the summary of results functionality on all pages, because we expect that people will be jumping around pages. We also have this summary on the first/Overview page, even though some may have not provided any information yet.

Addition: If the text currently displayed for the About/Start page is relevant to all users of this page, then I suggest to make it a real paragraph/intro in the main body of this page. If it is only relevant to people new to the tool, then maybe it belongs on the first/Overview page?

**Comment by hidde** [comment]
Resolution: 

* we'll display the same evaluation box content that is on the Principle pages, with added benefit of seeing conformance target changes in real time.

* we'll remove the instructional text as it somewhat states the obvious.
