### ISSUE TITLE
add footer and Acknowledgements page and Help improve this page box

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#156]
(I'll help with content for footer)

**Comment by hidde** [comment]
Added a “help improve” box and footer. 

I'm not sure if we should have an Ack page and/or what should go in it. 

Content suggestions for footer welcome. 

cc @nitedog

**Comment by slhenry** [comment]
Good start! Footer tweaks:

* [ ] change:
> Developed with input from the Education and Outreach Working Group (EOWG). 

to:
> ```Developed by the Education and Outreach Working Group (<a href="http://www.w3.org/WAI/EO/">EOWG</a>) with support from the <a href="https://www.w3.org/WAI/about/projects/wai-guide/">WAI-Guide</a> project funded by the European Commission (EC) under the Horizon 2020 program (Grant Agreement 822245).```

(I'll send separate message about Acknowledgments.)

**Comment by hidde** [comment]
Closed after I merged in https://github.com/w3c/wai-atag-report-tool/pull/167

**Comment by slhenry** [comment]
hi @hidde per "ART Acknowledgements" e-mail on 22 June 2020, Please change in the footer:

> Editor: [Hidde de Vries](https://www.w3.org/People/hidde/). 

to:

> Developer and Editor: [Hidde de Vries](https://www.w3.org/People/hidde/). Contributors: [Shadi Abou-Zahra](https://www.w3.org/People/shadi/), [Shawn Lawton Henry](https://www.w3.org/People/Shawn/), Eric Eggert, Kevin White, and Daniel Montalvo. [Acknowledgements](@@) lists additional contributors.

And delete from the end:
>  Acknowledgements for ATAG Report Tool

**Comment by hidde** [comment]
Thanks Shawn, updating this! Have left “Developer and Editor” and “Contributors” bold.
