### ISSUE TITLE
Fix unwanted whitespace in Prettier/HTML output

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#163]
* [ ] delete extra space before comma in Overview page:
> You can format your evaluation with Markdown , so that you can use lists, links and code examples.

* [ ] delete space before colons in field labels

**Comment by hidde** [comment]
This is our automated code formatter being over-excited… it inserts this space to make the code formatting consistent, without realising that space is meaningful in HTML. Will address!

**Comment by hidde** [comment]
Filed an issue for this in https://github.com/sveltejs/prettier-plugin-svelte/issues/103. In the meantime, I will remove Prettier, the code formatter from this project, hopefully to readd it at some point, because it is super helpful in ensuring all our code looks the same.
