### ISSUE TITLE
[!!] Start New Report???

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-atag-report-tool#169]
Besides opening a different browser, or completely clearing my browser cache (which I don't want to do), I am not sure how to start a new report. There is no way to remove my data and start another report for a new tool.

**Comment by slhenry** [comment]
There was discussion around this. I think at one point, there was a "Start New Report" button in the Your Evaluation box, and Kevin had reasons against that.

I thought we were add a "Start New Report" button on the first Overview page?

**Comment by bakkenb** [comment]
Yep, I remember the agreement to remove that from the Your Report box. I think I may have been out when it was discussed where it should be instead. I am hoping that it was not decided to do away with it altogether as that functionality is needed.

**Comment by hidde** [comment]
My bad, it was supposed to be on the overview page, but I had accidentally removed when I updated the logic that decides what to show.
