### ISSUE TITLE
Title/Name of tool

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#21]
I see this as a placeholder:
**ATAG Conformance Evaluation Report Tool (ACERT)**

That seems unnecessarily complex. Also, I've heard discomfort that "ACERT" is too similar to "CERTification".

Brainstorms for other names:
* **ATAG Report Tool (ART)**   ... _(I notice this is used throughout the [survey ](https://www.w3.org/2002/09/wbs/35532/acert-1/) :-)_
* ... _(will add more)_

**Comment by hidde** [comment]
I hadn't made the link with certification when I suggested ACERT… I think that's, in addition to the full name being overly complex (+1 to that), a strong case against the abbreviation. 

I like ART, as it also works well abbreviated. I can picture people say, for instance, “The W3C has made a great ATAG Report Tool!”. It doesn't include “evaluation”, but I think “report” has that connotation pretty much.

Other suggestions welcome, I personally struggle to come up with things that are shorter or more clear than ATAG Report Tool / ART.

**Comment by hidde** [comment]
Decided on ATAG Report Tool for now, recorded in [Decisions document](https://github.com/w3c/wai-authoring-tools/wiki/Decisions/), can revisit when needed.
