### ISSUE TITLE
Should we link to individual SCs?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#22]
cc @nitedog 

Why? 
- We have the name of number of the SC displayed anyway, so might as well save people a Google search and have it be a direct link

Why not?
- Too many links
- We already have the full text in the report tool, finding it in the spec doesn't add anything

**Comment by hidde** [comment]
Update: Added extra reason for why not: we already have full text in the report tool.

**Comment by iadawn** [comment]
The full text does not include a link to the "Implementing" link. This content adds more to the understanding of people and is worth making it easily findable

**Comment by hidde** [comment]
Great point @iadawn, have created new issue for this.

**Comment by hidde** [comment]
We now link to implementing instead of SC. Closing this issue.
