### ISSUE TITLE
Use simplified header

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#23]
We're currently using the full WAI website header. That's a lot of links and a lot of space taking attention away from the main event, this resource may qualify for using a (yet to be determined) smaller WAI header. 

See issue https://github.com/w3c/wai-website/issues/195 for the wider WAI issue.

cc @nitedog

**Comment by hidde** [comment]
Adding the progress indication to this issue: 

> We're currently reusing regular WAI sub navigation…
> 
> <img width="291" alt="screenshot of left hand navigation" src="https://user-images.githubusercontent.com/178782/73732670-e2627500-473a-11ea-8740-7b2db4e1495e.png">
> 
> …but functionally, this is something different, so it warrants a design specific for that function.

**Comment by hidde** [comment]
It's proven tricky to create something that is _horizontal_ and fits all the “steps” we have in this tool.

[My proposal](https://atag-report-tool-35d3k40bz.now.sh/) - I think I've found a good way that works well with the updated, simplified header. 

This updates the header to be like the one in the WCAG EM Report Tool. Rationale of why this is good: 

- is 'short' (not tall), so takes no space away 
- has only minimum necessary, so that it needs no cognitive load and we have a small DOM (good for AT users)

**Comment by slhenry** [comment]
re-opened per https://github.com/w3c/wai-website/issues/195#issuecomment-622517955

**Comment by hidde** [comment]
I've added a number of suggestions in https://github.com/w3c/wai-website/issues/195#issuecomment-634759317.

**Comment by hidde** [comment]
Agreed with @slhenry we'll use first suggestion in https://github.com/w3c/wai-website/issues/195#issuecomment-634759317.
