### ISSUE TITLE
Save evaluation locally 

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#26]
Using `localStorage` or some other mechanism, so that people don't need to do their evaluation in one sitting.

(cc @yatil)

**Comment by hidde** [comment]
I've implemented this in https://github.com/w3c/wai-atag-report-tool/pull/38, did not immediately merge it so that @yatil can have a look, plan to merge sometime next week.

**Comment by yatil** [comment]
Ive linked the PR to here :-) Because I can!

**Comment by hidde** [comment]
> Successfully merging a pull request may close this issue. 

Ominous!
