### ISSUE TITLE
Add Markdown support to 'Observations'

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#46]
So that people can add things like links, images and lists to make their report easier to act on.

**Comment by hidde** [comment]
This would also allow for code examples!

**Comment by iadawn** [comment]
Would be good to include some instructions that Markdown is available and where to get formatting information

**Comment by hidde** [comment]
@iadawn thanks! I've currently implemented this by having the words “Markdown supported” visible with each observations box, as well as links to the Markdown syntax documentation, see screenshot below for a visual representation of that.

<img width="542" alt="" src="https://user-images.githubusercontent.com/178782/77765869-29842c80-703f-11ea-8095-ae8757ddcfb1.png">
