### ISSUE TITLE
Add Tool URL to “Your Evaluation”

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-atag-report-tool#52]
Is it worth (or has it been considered) adding in the URL for the tool being evaluated?

**Comment by hidde** [comment]
Thanks! Just to make sure, you mean URL of the tool's website?

**Comment by iadawn** [comment]
Yes, was just thinking about the meta content that is available in the EM Reporting Tool and the Authoring Tools list. Would be useful to align up a bit with that and URL seemed the minimum.

**Comment by hidde** [comment]
Thanks, have added URL in https://github.com/w3c/wai-atag-report-tool/pull/55.
