### ISSUE TITLE
inconsistent use of ATAG numbering

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#57]
Example of current numbering:

- Navigation: "A.3"
- Main heading: "UI operable" (with reference to A.3 below that)
- Guideline: "A.3.1: Provide keyboard access to authoring features"
- Success Criteria: "Keyboard Access (Minimum)" (with references to "A.3.1.1 in later links and form labels)
- Forward/back button: "UI operable"

This inconsistent explicit and implicit use of ATAG numbering is confusing. I find myself consistently trying to process what comes from ATAG and what not, and how the different pieces of content relate to each other. In particular, the introduction of new handles (ie. "UI operable") that is not part of ATAG and inconsistently associated with A.3 (see issue #56) increases this confusion.

Suggested numbering:

- Navigation: "A.3"
- Main heading: "A.3: Editing-views are operable"
- Guideline: "A.3.1: Provide keyboard access to authoring features"
- Success Criteria: "A.3.1.1 Keyboard Access (Minimum)"
- Forward/back button: "A.3"

**Comment by hidde** [comment]
Agree with all, except… 

how would you feel if forward/back button would show: “A.3: Editing-views are operable” rather than just A.3?

**Comment by hidde** [comment]
Actually, I tried it with just A.3 and like the simplicity so agree with the suggestion. I had already made the other changes, so that closes this issue.
