### ISSUE TITLE
better representation of progress in the navigation bar

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#61]
Wondering if there can be some sort of progress representation in the navigation bar? For example to have small triangles from one step to the next, rather than each step being just a box?

**Comment by hidde** [comment]
Conceptually, I feel the navigation bar can be understood _with_ or _without_ progress. People can go through the application in the order we intended (and I think it is likely they will), but they can also choose not to (i.e. jump straight to principle B.2, change something there, then go to results).

So I would prefer to keep the navigation bar neutral with regards to whether it indicates progress or not.

I think there is a more meaningful kind of progress we could display: a bar chart that displays the percentage of success criteria that have been reported. We do that in words now, but it can be shown as a bar chart, too.

What do you think of that?

**Comment by nitedog** [comment]
I personally think that a bar chart is way too overblown way of presenting progress. I would prefer to have something more subtle but will go with the majority.

**Comment by hidde** [comment]
Thanks, in that case I will leave it as it is now.
