### ISSUE TITLE
[minor] avoid use of "step" in the URI

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#62]
We do not really have steps in this tool, so maybe should also avoid it in the URI? Maybe just use the same page name, like A.3 or A3 instead?

**Comment by hidde** [comment]
I think while in ATAG they are not steps, I think in the mental model of users using this tool they are steps. I would be in favour of having 'step' in more places. But since we currently only have them in the URI, happy to remove it from there too.

**Comment by hidde** [comment]
Have removed from URL and some hidden text that still said 'step'.
