### ISSUE TITLE
[minor] use of "Start" in page title

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#63]
Most page titles use page name followed by "ATAG Conformance Evaluation Report Tool", which makes sense for a multi-page form. However, for the first page, I wonder if we need any such prefix? Maybe "ATAG Conformance Evaluation Report Tool" is sufficient without "Start" or such?

**Comment by hidde** [comment]
I think “Start” confirms for users:

* this is a process, because it has a start
* this is where it starts
* it is different from the pages that share the same first bit of the title

My vote would be for keeping “Start”.

**Comment by nitedog** [comment]
I don't feel strongly, happy to go with the majority.

**Comment by hidde** [comment]
This is no longer relevant as we have discussed in larger group and now call it Overview. Thanks for starting the issue!
