### ISSUE TITLE
Structuring results table

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#64]
Right now all results are presented in one long table. I wonder if this table should be divided into Principles at least? Maybe also Guidelines?

**Comment by slhenry** [comment]
I support keeping it one table -- a lot easier to manipulate outside of the tool.

For example, some users might paste results into a spreadsheet and want to sort it all by Result.

Also, most common strategy for people with low vision is to save page and open in Word and then re-format. It would be more work and annoying if separate tables.
(Yes, I know, better to do in HTML and CSS then it wouldn't matter, but most don't.)

I think Daniel's opinion was one table better for some?most screen readers users, too.

**Comment by slhenry** [comment]
( @hidde I see you have "gathering EOWG input" as a label, but this didn't get listed for EOWG to comment on. If want more input, we should add to Work for this Week, and let EOWG know. )

**Comment by bakkenb** [comment]
I feel it could use more input. In the survey I commented that it would be nice if the table was sort-able. That way if a user wants to look at those that were "failed" at the top they could. Or those with no response, etc. Maybe opening a can of worms though.

**Comment by nitedog** [comment]
It seems that several people are happier with all data in one table, and may even like sorting functionality in later versions of the tool. Fair enough. What about the downloadable HTML report, should this also be one table or split out into sections?

**Comment by slhenry** [comment]
> What about the downloadable HTML report, should this also be one table or split out into sections?

My comment above applies to downloadable HTML report, too -- "I support keeping it one table -- a lot easier to manipulate outside of the tool."

**Comment by hidde** [comment]
Thinking from an auditor perspective… I can imagine lots of other ways to format the data, but think we should pick one and “one table with everything” seems like a good pick to me.

As an auditor, I would probably get the JSON and turn it into the HTML I want, as a larger auditing firm I might even build my own tool to turn JSON into my company style reports (which is a use case we're catering for with the JSON).

**Comment by nitedog** [comment]
OK. Changing the HTML output at a later stage, if needed, should be fairly easy too.

**Comment by hidde** [comment]
(@bakkenb side note: I have created an issue for your survey comment on making the table sortable https://github.com/w3c/wai-atag-report-tool/issues/88)

**Comment by mpalmersg** [comment]
I think a single table is far better for anyone trying to manipulate the information outside of the report itself.

**Comment by hidde** [comment]
Thanks all, a single table it is!
