### ISSUE TITLE
"Your name" and "Your organization"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#66]
On "Your Evaluation" page, I'm not sure about the use of "your". While we want to avoid the use of passive language where we can, there are often reasons why "your" may not apply in this context. For example, I'm hired to do an evaluation for an organization not for my own.

I suggest:

- Name of evaluator (may also be the name of an organization)
- Organization (for whom the evaluation is carried out)

Also, change "About your evaluation" to "About the authoring tool" and "About you" to "About the evaluation".

PS: note misspelling "organisation" instead of "organization" (US instead of GB spelling)

**Comment by hidde** [comment]
Have updated this.
