### ISSUE TITLE
Should all fields from "Your Evaluation" always show up in Report?

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#71]
The information that users enter in "Your Evaluation" page should also appear in the resulting report.

**Comment by hidde** [comment]
It does, but only if it is not missing.  

Would you prefer the fields to always show up, with default values like “Not supplied” or something like that?

I have a slight preference for only showing these fields when they have been supplied and leaving each out whenever it was not supplied.

**Comment by nitedog** [comment]
Hmm, good point. Not sure. Maybe there are minimal expectations like tool name at least?

**Comment by hidde** [comment]
But if the user did not supply it, what should we display (if not nothing?)?

**Comment by nitedog** [comment]
I think displaying something like "Tool name: <none>" or just "Tool name: " should be fine.

**Comment by hidde** [comment]
Two open questions:

* If meta data is left empty, should it show up _on the Report page_ (i.e. you don't add tool name, should 'tool name' show up on the report?)
* If meta data is left empty, should it show up in the HTML or JSON download?

**Comment by hidde** [comment]
Related, about which meta fields we should have at all: https://github.com/w3c/wai-atag-report-tool/issues/65

**Comment by bakkenb** [comment]
On the current Your Evaluation page I think that the "Name" field should be titled "Tool Name" instead. I think this field should also be required so that it always shows up on the report and json file. The data should always be tied to a name of a tool that was measured.

I feel that the other three fields should not be required data, and if no data is included, then the fields do not show up on the report or in the json file.

**Comment by slhenry** [comment]
[EOWG discussion 24 April](https://www.w3.org/2020/04/24-eo-minutes.html#item02)

**Comment by hidde** [comment]
Resolving this in the following way:

* Always display all fields in the Report page, with “Not provided” if not provided
* Move “ATAG Report Tool version” as small print to the bottom of the page
* Provide “Edit” link for general information
