### ISSUE TITLE
Provide as “download in HTML” functionality

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#72]
Use case: someone wants to download the report as HTML, customize the report, print it, etc.

**Comment by hidde** [comment]
Great idea! 

I have two ideas:

* resort to letting user use browser functionality to save HTML
* display a `textarea` in an expand/collapse that contains the HTML for easy copy pasting

What do you think? Or do we just want the browser to download a HTML file?

**Comment by nitedog** [comment]
I personally think it should be a download function like in the WCAG-EM Report Tool. Using the browser "save-as HTML" will usually save lots of unwanted navigation, styles, and such, and providing the raw HTML in a textarea is probably too cody for some people. I think in a download function you can ensure that only the report content (without any of the surrounding navigation and WAI styling etc.) is returned to the user.

**Comment by hidde** [comment]
First pass at this added.

To do: 

* [ ] Remove edit links and links to SCs from outputted report
* [ ] Add missing doctype to outputted HTML document

**Comment by slhenry** [comment]
Ideally the HTML version looks decent, too. Some users might actually use it as is without customizing it.

**Comment by hidde** [comment]
I've built this feature as a strictly HTML only report, so that people can customise it (adding styles to that would oppose that goal, I've made an effort to strip it from all the styles). 

I think the “use as is” use case is covered by the “Save as HTML” feature of the browser (ie pressing “CTRL + S” / “Command S”, so we would not need to specifically cater for that?

**Comment by nitedog** [comment]
I agree that the report should be plain HTML without styling (except for maybe table-border?). Yet the text and order of the headings are likely a big part of "looking decent".

**Comment by hidde** [comment]
> I agree that the report should be plain HTML without styling

OK.

>  (except for maybe table-border?) 

Hm, this expands the scope, I'd propose we don't.

>  Yet the text and order of the headings are likely a big part of "looking decent".

They are exactly the same as the report we display.

**Comment by slhenry** [comment]
I think table borders are a requirement for accessibility and usability.

**Comment by hidde** [comment]
> I think table borders are a requirement for accessibility and usability.

Arguably a UAAG concern, haha! In any case, I agree with you both that it is useful to add. Have just added a border to the table. I've done this “in HTML” (inline style) by adding `border=1` and `style="border-collapse:collapse"` attributes to the `table`, should be easy enough to remove for those who don't want it.

Also updated:

* added H1, same as `<title>` of the page. Used “Authoring Tool Accessibility Report” as suggested by @slhenry in https://github.com/w3c/wai-atag-report-tool/issues/129 
* added doctype and charset for extra valid HTML
* stripped HTML from: classes, ARIA attributes, buttons, inputs, edit column

I believe this concludes the “Download as HTML” work for now, feel free to reopen if I missed anything, thanks for the feedback!
