### ISSUE TITLE
[Medium] Condensing messages

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-atag-report-tool#74]
"No existing evaluation" is the wording we use when the system does not find an evaluation. Why are we using "existing"? Can't we make it more succinct by just saying "No evaluations found"?"

**Comment by hidde** [comment]
Have changed this to be: “Welcome to the ATAG Report Tool.”, with then the buttons to start and import. What do you think of that?

**Comment by hidde** [comment]
Closing this issue as I have now completely removed the “No existing found” wording. Thanks again for the feedback!
