### ISSUE TITLE
[High] Use of placeholder that seems distracting

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-atag-report-tool#79]
In "Your evaluation" -- "Website" edit field, the placeholder contains a value of " https\://".

When a URL is introduced without https://, validation seems to fail.

I suggest:

1. Not use placeholder at all. Even when we use it, it is not clear to me the message that it is conveying (currently users need to type https:// themselves).
2. Include a message that the URL needs to be preceded by https:// (or make it we by prefilling that string so that users don't have to type it.

Or

1. Let users decide if they want to use https:// or not and take care of this behind the scenes.

**Comment by hidde** [comment]
Thanks Daniel, considering your points, I have resorted to removing the placeholder altogether.
