### ISSUE TITLE
"Your evaluation" box obscures page content.

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#81]
"Your evaluation" box obscures page content.

![image](https://user-images.githubusercontent.com/6991814/79503469-d3c7f200-7ff6-11ea-90c0-620031dddf43.png)

**Comment by hidde** [comment]
Hi Shawn,

Apologies, I have just fixed this! We now only do `sticky` in the wider layout (where it only obscures whitespaces rather than important content :-) ). This was always the intention, but I specified the wrong width.
