### ISSUE TITLE
Add “edit” link from Markdown preview in Results

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#87]
HB, SR reported there should be an easy way to return to the field from the Markdown preview.

The Markdown preview is really a link to a cell in the Results table.

Proposal: to add an “edit” link where the Markdown is previewed, so that one can go straight to editing that criterion, whether it is to go “back” or not.

**Comment by hidde** [comment]
More use cases (via @nitedog): 

* Someone has created a full report and wants to review it, then make an edit
* Someone is very well versed in ATAG and goes straight to report

**Comment by hidde** [comment]
Mockup: <img width="1199" alt="results screen with table of results, each row has a cell at the end that contains an edit icon" src="https://user-images.githubusercontent.com/178782/80106907-c07ad080-857a-11ea-8052-456b0ed0f5ec.png">

**Comment by bakkenb** [comment]
Currently, I like the implementation shown above.

**Comment by hidde** [comment]
Thanks, I have merged these changes into the latest version!
