### ISSUE TITLE
ATAG tool link displays a blank page in IE and Edge

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-atag-report-tool#90]
https://atag-report-tool.hdv.now.sh/

Microsoft Edge 44.17763.831.0 - and IE 11.1158.17763.0 displays WAI header and footer only

**Comment by hidde** [comment]
Many thanks for reporting, will investigate and fix!

**Comment by hidde** [comment]
This is now fixed for Edge, not (yet) for IE11.

**Comment by hidde** [comment]
Closing this in favour of this new issue that is about IE11 support only https://github.com/w3c/wai-atag-report-tool/issues/90
