### ISSUE TITLE
Report summary [medium]

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#94]
I'm thinking that some users would find it useful to have a summary of the results. The table itself could get pretty long with lots of "Observations", and it'd be good to easily see an overview at the top of the report.

I'm not sure how the info best organized and presented -- by Level? by Result? It be nice to look at rough draft options...

[updated] one possibility (that i'm not necessarily suggesting)
* Passed: A.3.2.3, A 3.2.3, …
* Failed: A.3.6.1, A.3.6.2
* Cannot tell: A.4.2.1, A.4.2.2, …
* Not applicable: B.2.4.2, B.2.4.3, …
* Not Checked: B.4.2.1, B.4.2.1, …

with those being linked -- probably to the table (where report reader could read more details, and report filler-out-ers could use the edit button to update)

**Comment by hidde** [comment]
Suggested visual design:

<img width="995" alt="" src="https://user-images.githubusercontent.com/178782/81660609-43d16880-943b-11ea-8a53-fb772f6ac960.png">

Or see it in action on the report page (make sure you have evaluated one or more items) https://atag-report-tool.hdv.now.sh/report

**Comment by slhenry** [comment]
I *mildy* don't like the visual treatment *and* I'd thinking it would be good to indicate Level.

However, I'm fine with as it.

**Comment by hidde** [comment]
Thanks, in that case let's leave it as is. I think adding Level will make it harder to scan.

**Comment by iadawn** [comment]
Appreciate this is closed but one thing to note is that the summary does not provide a scannable total of pass/fail/cannot tell. It might be useful to have something like:

- Passed (15/30): A.1.1.1 A.2.21
- Failed (8/30): ...
- Cannot tell (7/30): ....

**Comment by slhenry** [comment]
+1 for including number of each.

maybe (15 of 52) rather than (15/52)? Or maybe we don't need the total -- since it's a consistent number -- and can just have the number (15)? I don't feel strongly either way

**Comment by hidde** [comment]
Thanks for the suggestion, @iadawn! 

I agree with @slhenry that the total might not be so useful as it is the same across all results.

Have updated it so that the numbers are now included.

<img width="525" alt="Summary - This report has results for 6 out of 63 Success Criteria. - Passed (2): A.3.1.2, A.3.1.4; Failed (3): A.1.1.1, A.2.1.1, A.3.1.3; Not checked (1): A.4.1.1" src="https://user-images.githubusercontent.com/178782/82634595-5cd9d680-9bfe-11ea-97bc-b1baf3af4c34.png">
