### ISSUE TITLE
info at top of report [low]

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#97]
1. I think not in DL -- it doesn't need to take up that much space. Also, I think the data is more important than the label, so that should be bold. I think:
> Tool Name: **Acme Web Creator**

2. "Created with ATAG Report Tool version"
I think this is not needed at all. Or, maybe small at the end of the report. Not at the top.

**Comment by hidde** [comment]
Updated top of report to take less space and have most important info (data) bold instead of label.

Moved “Created with ATAG Report Tool version” to end of report in small text, completely agree it is a lot less important.

**Comment by slhenry** [comment]
Additional perspectives. Others may differ.

![image](https://user-images.githubusercontent.com/6991814/80819192-20383380-8b9a-11ea-8d60-ef2726a482dc.png)

Current design above is hard for me to process. My visual **focus jumps all around** trying to figure out the relationship between the words and phrases.

This is a bit better:
![image](https://user-images.githubusercontent.com/6991814/80819230-37772100-8b9a-11ea-993e-601192897b60.png)

**This is easiest: !**
![image](https://user-images.githubusercontent.com/6991814/80818981-bfa8f680-8b99-11ea-8739-15261122c332.png)

**Comment by hidde** [comment]
OK, have removed the indentation from the values for easier reading experience.

Applying Gestalt law of proximity, it seems to me some users may benefit from Evaluator and Organisation being close to each other. This works best with more whitespace, but even with long names and not so much whitespace, it seems we get most proximity when we leave the items grouped as they are.

Example of current, with indentation removed:

<img width="910" alt="" src="https://user-images.githubusercontent.com/178782/81653005-c4409b00-9434-11ea-82e2-40cded4a51cc.png">

Example of current with much longer names, there is still more space between the columns than between the items:

<img width="997" alt="" src="https://user-images.githubusercontent.com/178782/81653083-d15d8a00-9434-11ea-8820-86b5dace5e40.png">

**Comment by slhenry** [comment]
I'm a huge proponent of proximity! (e.g., I championed this tip on [whitespace and proximity](https://www.w3.org/WAI/tips/designing/#use-headings-and-spacing-to-group-related-content))

My examples above **also** use spacing and proximity to group the information.

I find the layout with the labels above the field very hard to process. Actually, not indented is even **worse** for me. I'm pretty sure that eye tracking would show that most users would also have more difficulty with the labels and data on different lines..

This isn't a showstopper, yet I'm hesitant to let it go without more feedback.

Perhaps ask for more input from EOWG participants?

**Comment by hidde** [comment]
Hm, would more space between the key/value pairs items help, e.g. more space between tool name and website? 

Or we can try just aligning horizontally with just one per line, as per your example above?

**Comment by slhenry** [comment]
One per line is easiest for my visual and cognitive processing. I'm happy to hear other perspectives.

**Comment by hidde** [comment]
Have now displayed them one by one; and side by side if there is space (~ more than 1000px available in the viewport width).

**Comment by slhenry** [comment]
[hi] Can you have less space between the label and the start of the data? "Conformance Target" is longes so would be good if all lined up just an m-dash or so after that. :-) This would improve usability overall, and especially for magnification users.

[low] I do think grouping with proximity and white space would be helpful -- though not super important. That is, less space between Tool Name and Website and also less space between Evaluator and Organization -- and/or more space between the different sets of fields -- like the mock-up under "This is easiest: !" [above](https://github.com/w3c/wai-atag-report-tool/issues/97#issuecomment-622445459)

[typo] "Tool Name :" _(space before colon)_

**Comment by hidde** [comment]
Thanks for the feedback, I can do that! 

The current gap is `3em`.

<img width="1046" alt="info at top screenshot with grid overlayed that shows 3em spacing" src="https://user-images.githubusercontent.com/178782/82635042-98c16b80-9bff-11ea-9ea5-0d809631778a.png">

This is with `1em`:

<img width="1097" alt="info at top screenshot, grid overlayed, now with 1em spacing6" src="https://user-images.githubusercontent.com/178782/82635079-b262b300-9bff-11ea-83d9-04f6d751b0aa.png">

Or without the grid overlayed:

<img width="984" alt="Screenshot 2020-05-22 at 07 40 52" src="https://user-images.githubusercontent.com/178782/82635131-d625f900-9bff-11ea-86fd-392e74601e13.png">

> [typo] "Tool Name :" (space before colon) 

Woops, adjusted (just after I took the screenshots above).

**Comment by hidde** [comment]
Closing this as I feel the feedback is addressed, feel free to comment if not of course.
